name: Rust Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: moonrepo/setup-rust@v1

      - name: Install dependencies
        run: |
          cargo build --release

      - name: Run tests
        run: |
          cargo test
